config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  get 'users/profile'
  get 'users/show'
  devise_for :users
  
  resources :posts do
    resources :comments
    resource :likes, only: :show
  end

  resources :comments

  resources :rooms do
    resources :messages, shallow: :true
    collection do
      post :search
    end
  end

  resources :embeds, only: [:create], constraints: { id: /[^\/]+/ } do
    collection do
      get :patterns
    end
  end
  
  resources :mentions, only: [:index]
  
  get ':username', to: 'users#profile', as: 'user_profile'  #user_path(user.username) gia na parw to profile enos user
  get 'user/:id', to: 'users#show', as: 'user'  # private chat room
  root 'posts#index'
end

app/models/message.rb
class Message < ApplicationRecord
  include ActionView::RecordIdentifier

  belongs_to :user  # kathe message anhkei se ena user
  belongs_to :room  # kathe message anhkei se ena room
  # gia na apotrepsw allous xrhstes na stelnoun mhnymata se private rooms pou den symmetexoun ws roommates kalw tin before_create
  before_create :check_if_roommate
  # den thelw na stelnw empty messages
  validates :body, presence: true, unless: -> { recordings.present? } # epitrepw to body na einai empty, mono ean exw recording(s) attached sto file_field

  has_many_attached :recordings, dependent: :destroy  # gia na mporw na steilw video recording

  validate :validate_recording_types  # kanw validation ta recordings pou stelnw (san attachments), wste na mhn mporei kapoios na steilei kati pera apo video h audio files
  
  has_noticed_notifications model_name: 'Notification' # noticed gem gia ta notifications

  # me ti dhmiourgia enos message, to kanw broadcast sto chat room  (Append gia na mpei katw sti lista twn messages tou room)
  after_create_commit do 
    send_notification # stelnw notification ston paralhpth tou mhnymatos ean einai private room
    # set the time of the latest message
    update_room_with_latest_message # kanw update to room wste na mporw na ta kanw sort me vash to teleutaio message
    broadcast_append_later_to room # kanw broadcast append to message sto room pou anhkei
  end

  after_destroy_commit do
    update_notification_count
    # kanw update to latest_message field tou room
    update_room_with_latest_message  # wste ean to mhnyma tou diegrapsa htan to teleutaio tou room na kanei update to room sti lista me ta rooms me to neotero latest message tou (dhladh to prohgoumeno apo auto pou diegrapsa)
    broadcast_remove_to room  # otan diagrafw ena mhnyma kanw broadcast remove apo to room pou anhkei
  end
  
  # apo ton browser einai adynato kapoios user na steilei mhnyma se private room sto opoio den symmetexei(roommmate)
  # gia na apotrepsw omws na mporei na steilei kapoios 3os apo to rails console, kanw auto to extra check.
  def check_if_roommate
    return unless room.is_private # gia na kanw ton elegxo parakatw, elegxw an to room einai private
    # alliws oloi oi users mporoun na steiloun message se public room

    is_roommate = Roommate.where(user_id: self.user.id, room_id: self.room.id).first
    throw :abort unless is_roommate
  end

  def update_room_with_latest_message
    unless room.destroyed? # elegxw oti den exei diagrafei to public room, wste na mhn exw error an den yparxei room kai kanw update to latest message time column
      room.update(latest_message: Time.now) # kanw update tin wra sto latest_message column tou room meta apo kathe created message
    end
  end

  private

  def validate_recording_types  # orizw poia file types epitrepetai na kanw upload mesw tou message form
    return unless recordings.attached?  # return an to message den periexei attached recordings

    acceptable_types = ["video/mp4", "video/webm", "video/quicktime", "video/mpeg", "audio/mpeg", "audio/mp4", "audio/webm", "audio/ogg", "audio/mp3", "audio/x-wav", "audio/wave", "audio/x-pn-wav"]

    recordings.each do |recording|  # gia kathe recording elegxw to content_type tou
      unless acceptable_types.include?(recording.content_type)  # an anevasw otidhpote allo, emfanizw to parakatw error
        errors.add(:recordings, 'can only be of type VIDEO: [webm, mp4, mpeg or quicktime] and AUDIO: [mp3, wav or ogg]')
      end
    end

  end

  def send_notification # otan exw ena private conversation me kapoion allo user, stelnw notification kathe fora pou tou stelnw neo mhnyma
    return unless room.is_private
    roommate = room.joined_roommates  # ena private conversation apoteleitai apo 2 users. pairnw tous users rou private room mesw tou joined_roommates pou exw orisei sto model tou Room 
    roommate.each do |user| # gia kathe user tou private room 
      next if user.eql?(self.user)  # den thelw na steilw notification ston current user, dhladh se auton pou stelnei to mhnyma alla mono ston recipient, opote kanw skip
      notification = MessageNotification.with(message: self, room:) # create a notification gia ton allo user o opoios einai o recipient tou mhnymatos, pernaw san message to idio to message kai san room to room tou message
      notification.deliver_later(user)  # to kanw deliver ston allo user
      broadcast_update_later_to(  # trigger ena turbo stream broadcast otan dhmiourgeitai ena message
        user, # gia na sigourepsw oti to notification tha paei mono ston user pou prepei na to dextei
        :notifications, # kanw set to broadcast channel sto user, :notifications KAI sto index page vazw ena turbo_stream_from current_user, :notifications
        target: "#{dom_id(user)}_#{dom_id(room)}_notifications",  # kanw update to notification counter sto target pou exw orisei sto partial _user_notifications
        partial: "users/notification_count",  # pernaw to partial pou thelw na kanw update ton counter
        locals: {
          count: room.notifications_as_room.where(type: MessageNotification.name, recipient: user).unread.count # pernaw ta locals, wste na allaksw to count twn unread notifications otan ena neo mhnyma stelnetai ston user
        }
      )
    end
  end

  def update_notification_count # opws kai sto send_notification
    # otan diagrafw ena message enos private room, ginetai destroyed kai to notification tou
    # gia na to kanw se real time, efoson enas user den to exei diavasei, kanw broadcast update ton arithmo twn unread notifications tou recipient tou message
    return unless room.is_private
    roommate = room.joined_roommates  
    roommate.each do |user|
      next if user.eql?(self.user)
      broadcast_update_to(
        user,
        :notifications,
        target: "#{dom_id(user)}_#{dom_id(room)}_notifications",
        partial: "users/notification_count",
        locals: {
          count: room.notifications_as_room.where(type: MessageNotification.name, recipient: user).unread.count # pernaw ta locals, wste na allaksw to count twn unread notifications otan ena neo mhnyma stelnetai ston user
        }
      )
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @message = current_user.messages.create(message_params) # kata th dhmiourgia pernaw san user ton current_user pou to stelnei

    unless @message.room.nil? #an to post exei diagrafei kai o user einai sto show h epixeirhsei na paei sto url tou, kanw redirect
      unless @message.save
        flash.now[:alert] = @message.errors.full_messages.join(', ')
        render turbo_stream:
          turbo_stream.prepend('flash', partial: 'shared/flash')
      end
    else
      redirect_to rooms_path, alert: "Chatroom was not found"
    end
  end

  def destroy # diagrafh enos message
    @message = Message.find(params[:id])
    # enas user mporei na diagrapsei mono ta mhnymata pou exei steilei o idios
    # enas admin mporei an diagrapsei ta mhnymata kai twn allwn xrhstwn
    if !current_user.admin? 
      if current_user != @message.user 
        redirect_to @message.room # an opoiosdhpote allos xrhsths peran tou message user epixeirhsei na diagrapsei message, ton kanw redirect
      else
        @message.destroy
      end
    else
      @message.destroy
    end
  end
  
  private

  def message_params
    params
      .require(:message)
      .permit(:body, recordings: [])  # pera apo to body, ena message mporei na exei kai attached recordings
      .merge(room_id: params[:room_id])  # opws kai sta comments
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<!-- forma dhmiourgias enos message pou anhkei se ena room, gia na ginei clear h forma sto submit xrhsimopoiw ton controller reset-form -->
<div class="form-group message-form">
  <%= form_with(model: [@chat_room, @message], remote: true, class:'d-flex',  # remote: true gia na kanw submit on enter
    data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }, id: "msg-form") do |f| %>
    <!-- O container ston opoio  emfanizw ta preview twn recordings prin kanw submit ti forma. -->
    <div id="preview-recordings" class="d-none card" data-controller="record-and-preview" data-action="record-and-preview#previewRecordings"></div>
    
    <!-- ta icons gia to video kai audio recording pou exw san button gia na ksekinhsw kai na stamathsw to video recording -->
    <!-- to xrhsimopoiw ston preview_uploads controller mesw tou id tou -->
    <%= content_tag(:i, nil, id: 'record-video-btn', class: 'bi bi-camera-video me-1 m-auto record-video-icon') %>
    <%= content_tag(:i, nil, id: 'record-audio-btn', class: 'bi bi-mic ms-2 me-2 m-auto record-audio-icon') %>

    
    <%= f.label :recordings, hidden: true %>  <!-- label gia to id tou input pou einai to "message_recordings" -->
    <!-- file_field gia na kanw upload ta recordings -->
    <!-- hidden: true gia na mhn kanei upload apeutheias arxeia apo ti syskeyh -->
    <!-- mesw tou controller preview_uploads otan kanw ena recording, to kanw attach se auto to file_field -->
    <!-- akouw gia change event, kai kathe fora pou prostithentai recordings sto file_field, kalw tin previewRecordings tou controller pou emfanizei ta previews twn recordings pou kanw attach -->
    <%= f.file_field(:recordings, hidden: true, multiple: true, data: { controller: "record-and-preview", action:"change->record-and-preview#previewRecordings"}) %> 
    
    <%= f.text_field :body, class: 'form-control message-body', autocomplete: 'off' %>  <!-- pedio gia to message body -->
    <!-- sto submit, kalw tin resetPreviews tou controller, wste na afairesw ta previews twn recordings pou molis ekana submit kathws kai ton container pou ta perieixe -->
    <%= f.submit "Send", data: {disable_with: false, controller: "record-and-preview", action:"click->record-and-preview#resetPreviews"}, class: 'btn btn-primary' %> 
  <% end %>
</div>

app/views/messages/_message.html.erb
<!-- pws emfanizw to message sto chat -->
<%= turbo_frame_tag message do %>
  <div class="message-container-user-<%= message.user.id %>"> <!-- orizw ena class gia na prosthesw styling ston container tou message, me vash to id tou user pou to dhmiourgei -->
  <!-- gia na exoun ta messages tou current_user allo styling (na einai deksia me allo xrwma), mporw na tropopoihsw to class sto application.html.erb mesw tou helper current_user -->
    <div class="chat-message-container message-user-<%= message.user.id %> user-role-<%= message.user.role%>">
      <div class="d-flex align-items-center justify-content-between">
        <%= render 'messages/user_avatar', user: message.user, message: message %> <!-- partial pou emfanizei to avatar kai to username tou user pou esteile to mhnyma -->
        <div class="d-none" 
             data-controller='check-message-author'
             data-check-message-author-author-id-value='<%= message.user.id %>'>  <!-- controller pou elegxei an o current user einai o message owner H admin, wste na emfanizw button gia na to kanei delete -->
          <%= button_to message_path(message), class: "btn btn-sm shadow-none", method: :delete, data: { confirm: "Are you sure?" } do %> <!-- destroy message -->
            <i class="bi bi-trash-fill msg-destroy"></i>
          <% end %>
        </div>
      </div>
      <div class="mt-1 ms-1 mb-0"><%= message.body %></div>
      <% if message.recordings.attached? %> <!-- pws emfanizw ta recordings pou exw kanei attach sto message form -->
      <div class="">
        <% message.recordings.each do |recording| %>
          <% if recording.video? %>
            <%= video_tag(url_for(recording), class: 'w-100 video-file', controls: '') %> <!-- sto video-file css class pernaw to height tou video wste otan ena mhnyma exei video recording, na mhn ephreazetai to height tou message otan kanw scroll sto bottom tou chat mesw tou controller -->
          <% elsif recording.audio?%>
            <%= audio_tag(url_for(recording), class: 'w-100', controls: '') %>
          <% end %>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/messages/_next_message_page.html.erb
<% if @more_pages %> <!-- idia logiki me to pagination pou exw se posts kai comments-->
  <%= turbo_frame_tag(
        "messages-page-#{@next_cursor}",
        loading: :lazy,
        src: url_for(cursor: @next_cursor), # to url_for me voithaei giati pairnei to current url analoga me poion contoller douleuw (users gia ta private rooms, kai rooms gia ta public rooms)
        # An epairna san src: room_path, den tha douleue gia ta private chats tou usersController kathws gia ekeina xreiazomai to user_path
        # tha eprepe na dhmiourghsw to idio partial view gia to user controller kai na pernaw san src to user_path kai sto index na elegxw ean to room einai private h oxi
        # px. sto index ->   if @chat_room.is_private 
        #                      render partial: "users/next_message_page"
        #                    else
        #                      render partial: "messages/next_message_page"
        #                    end
        target: "_top"
      ) do %>
    <div class="d-flex justify-content-center loading">
      <div class="spinner-border text-secondary" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
    </div>
  <% end %>
<% else %>
  <p class=" mb-2 text-center fw-bold fst-italic">You've reached the end of this room's messages.</p>
<% end %>

app/views/messages/_user_avatar.html.erb
<div class="dropdown">
  <div class="d-flex align-items-center">
    <a href="#" class="text-decoration-none" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown">
      <div class="d-flex align-items-center">
        <% if user.avatar.attached? %>
          <%= image_tag(user.avatar.variant(resize_to_limit: [50, 50]).processed, class: "chat_user_icon") %>
        <% else %>
          <%= image_tag user.gravatar_url, width: 50, class: "chat_user_icon" %>
        <% end %>
        <div class="d-flex justify-content-between align-items-center text-white">
          <strong class="me-2 username-<%= user.role%>"> <%= user.username %> </strong>
        </div>
      </div>
    </a>
    <span class="dot"> </span> <small class="ms-2 msg-time"> <%= time_ago_in_words(message.created_at) %> ago </small>
    <ul class="dropdown-menu dropdown-color" aria-labelledby="dropdownMenuLink">
      <div class="d-flex justify-content-center p-2">
        <div class="p-2">
          <% if user.avatar.attached? %>
            <%= image_tag user.avatar.variant(resize: "100x100!"), class: "rounded-circle" %>
          <% else %>
            <%= image_tag user.gravatar_url, width: 100, class: "rounded-circle" %>
          <% end %>
        </div>
      
        <div class="card bg-dark p-1 m-1 text-white">
          <strong class="dropdown-username-<%= user.role %> border-bottom border-secondary text-center">
            <%= user.username %>
          </strong>
          <span class="text-center fst-italic">
            Joined: <%= user.created_at.strftime("%B %Y") %>
          </span>
          <% if user.admin? %>
            <span class="mt-1 m-auto badge rounded-pill bg-success">ADMIN</span>
          <% end %>
        </div>
      </div>
      <li><%= link_to user, class:'dropdown-item rounded me-1 d-flex justify-content-between', data: {turbo: "false"} do %>
            Direct Message <i class="bi bi-envelope-fill"></i>
      <% end %></li>
      <li><a class="dropdown-item rounded me-1 d-flex justify-content-between" href="<%= user_profile_path(user.username) %>" target="_top">View Profile <i class="bi bi-person-circle"></i></a></li>

    </ul>
  </div>
</div>

app/views/messages/scrollable_message_list.html.erb
<!-- idia logiki me to pagination pou exw se posts kai comments, me th diafora oti exw pagination kanontas scrolling pros ta panw-->
<!-- ara panw apo ta messages tha exw to turbo frame to opoio otan ginetai visible kanontas scroll up opou teleiwnei i lista twn messages tis selidas kanei lazy load ta messages tis epomenhs -->
<%= turbo_frame_tag "messages-page-#{@cursor}" do %>
  <%= render partial: "messages/next_message_page" %>
  <%= render @messages %>
<% end %>