config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  get 'users/profile'
  get 'users/show'
  devise_for :users
  
  resources :posts do
    resources :comments
    resource :likes, only: :show
  end

  resources :comments

  resources :rooms do
    resources :messages, shallow: :true
    collection do
      post :search
    end
  end

  resources :embeds, only: [:create], constraints: { id: /[^\/]+/ } do
    collection do
      get :patterns
    end
  end
  
  resources :mentions, only: [:index]
  
  get ':username', to: 'users#profile', as: 'user_profile'  #user_path(user.username) gia na parw to profile enos user
  get 'user/:id', to: 'users#show', as: 'user'  # private chat room
  root 'posts#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  include ActionView::RecordIdentifier # gia na xrhsimopoiw to dom_id se ena model
  include ApplicationHelper

  belongs_to :post, counter_cache: true # kathe comment anhkei se ena post.
  belongs_to :user # kathe comment anhkei se ena user
  belongs_to :parent, class_name: 'Comment', optional: true # otan apantaw se ena comment, thelw na pairnw to comment_id sto opoio apantaw san parent_id
  # epeidh den yparxei class parent, prepei na orisw to class_name
  # 
  has_many :comments, foreign_key: :parent_id, dependent: :destroy # ena comment mporei na einai parent sta comments pou einai apanthseis se auto
  # xreiazomai to foreign_key wste na mporw na parw th lista me ta comments enos sygkekrimenou comment.
  # otan diagrafw ena parent comment, diagrafontai kai ola ta children tou

  validates :body, presence: true # prepei na mhn einai adeio

  # dokimh gia soft delete, antikatastash me "comment deleted" message anti gia diagrafh
  #def destroy
  #  update(deleted_at: Time.zone.now)
  #end

  #broadcast to neo comment se olous tous users
  after_create_commit do
    # to neo comment exei parent, to parent einai true, ara tha ginei prepend sto target dom_id(comment)_comments, dhladh katw apo to parent comment
    # alliws to kanw prepend stin koryfh ths listas twn comments pou den exoun parent, sto target dom_id(post)_comments, afou einai comment sto post kai oxi se allo comment
    
    broadcast_prepend_to [post, :comments], target: "#{dom_id(parent || post)}_comments", partial: "comments/comment_with_replies"
    update_com_counter
  end

  # broadcast update tou comment se olous tous users
  after_update_commit do
    broadcast_replace_to self
  end

  # broadcast th diagrafh tou comment se olous tous users
  after_destroy_commit do
    broadcast_remove_to self
    broadcast_action_to self, action: :remove, target: "#{dom_id(self)}_with_comments"
    if !post.nil?
      update_com_counter
    end
  end

  private

  # kanw broadcast to neo arithmo comments, gia kathe create h destroy.
  def update_com_counter
    broadcast_update_to("posts", target: "#{dom_id(post)}_comments_counter", html: post.comments_count) # target sto post partial, pou einai link_to post#show kai ananewnetai kai sto index kai sto show
    broadcast_update_to("posts", target: "comments_counter", partial: 'comments/count', locals: { count: post.comments_count }) # target sto show tou post
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include ActionView::RecordIdentifier
  #before_action :is_author?, only: [:edit, :update]
  
  def create
    #create neo comment gia to post apo ton current_user
    @comment = current_user.comments.new(comment_params) # pernaw kateutheian to id tou current_user
    
    if @comment.post.nil? #an to post exei diagrafei kai o user einai sto show h epixeirhsei na paei sto url tou, kanw redirect
      redirect_to posts_path, alert: "Post was not found"
    else
      respond_to do |format|
        if @comment.save
          flash.now[:notice] = "Comment #{@comment.id} was successfully created."
          format.turbo_stream do
            render turbo_stream: [
              # to neo comment ginetai kateutheian broadcast apo to model comment.rb se olous tous users
              # edw kanw render to flash message mono ston user pou kanei to comment
              helpers.render_flash_messages 
            ]
          end
          format.html { redirect_to @comment.post, notice: 'Comment was successfully created.' }
        else
          flash.now[:alert] = 'Something went wrong...'
          format.turbo_stream do
            render turbo_stream: [
              # kanw render to flash message ston user
              helpers.render_flash_messages
            ]
          end
        end
      end
    end
  end

  def show
    #@comment = current_user.comments.find(params[:id]) # otan eixa to is_author?
    @comment = Comment.find(params[:id]) # oloi oi users mporoun na doun to show page enos comment
  end

  def edit
    @comment = Comment.find(params[:id])
  end
  
  def update
    # update to comment tou post apo ton current_user
    #@comment = current_user.comments.find(params[:id]) #mono o comment owner mporei na kanei update ena comment
    @comment = Comment.find(params[:id])
    #to xrhsimopoiousa otan edeixna ta buttons [edit, delete] se olous tous users kai oxi mono ston owner
    if current_user != @comment.user
      respond_to do |format|
        format.turbo_stream { flash.now[:alert] = "You don't have the rights to edit this comment." }
        format.html { redirect_to @comment, alert: "You don't have the rights to edit this comment." }
      end
    else
      if @comment.update(comment_params)
        respond_to do |format|
          # update.turbo_stream.erb
          # to updated comment ginetai kateutheian broadcast apo to model comment.rb se olous tous users
          format.turbo_stream { flash.now[:notice] = "Comment #{@comment.id} was successfully updated." }
          format.html { redirect_to @comment }
        end
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def destroy
    # delete to comment tou post apo ton current_user
    #@comment = current_user.comments.find(params[:id]) otan eixa to is_author?
    @comment = Comment.find(params[:id])

    #to xrhsimopoiousa otan edeixna ta buttons [edit, delete] se olous tous users kai oxi mono ston owner
    if current_user != @comment.user
      respond_to do |format|
        format.turbo_stream { flash.now[:alert] = "You don't have the rights to delete this comment." }
        format.html { redirect_to @comment.post, alert: "You don't have the rights to delete this comment." }
      end
    else
      @comment.destroy

      respond_to do |format|
        # destroy.turbo_stream.erb
        # to comment ginetai removed gia olous tous users mesa tou broadcast apo to comment.rb
        format.turbo_stream { flash.now[:notice] = "Comment #{@comment.id} was successfully deleted." }
        format.html { redirect_to @comment.post }
      end
    end
  end
  
  private

  def comment_params
    params
      .require(:comment)
      .permit(:body, :parent_id)  # permits parent_id gia na to pernaw sti forma tou comment
      .merge(post_id: params[:post_id]) # to post_comments_path periexei tis plhrofories tou post sto opoio dhmiourgw to comment,
                                        # opote kanw merge tis params pou pernaw edw, wste na periexoun to post_id apo to post params
  end

  # mono o comment owner mporei na kanei edit kai delete to comment tou
  # an prospathisei na kanei edit kapoios allos, ton kanw redirect sto post tou comment kai kanw render to flash message
  def is_author?
    @comment = Comment.find(params[:id])
    redirect_to @comment.post, alert: "You don't have the rights to edit or delete this comment." unless @comment.user == current_user
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<!-- partial gia tin emfanish tou comment -->
<%= turbo_stream_from comment %> <!-- stream pou akouei gia updates sto comment -->
<%= turbo_frame_tag comment do %> <!-- perikleiw kathe comment me ena frame gia na kanw update to frame otan kanw edit -->
  <div class="card mt-2">
    <div class="d-flex flex-row rounded comment-row p-2">
      <% if comment.deleted_at.present? %> <!-- soft-delete / den to xrhsimopoiw -->
        <i><%= comment.user.username %>'s comment has been deleted</i> <!-- no use -->
      <% else %>
        <div class="p-1">
          <%= render partial: 'comments/comment_avatar', locals: { comment: comment } %> <!-- kanw render to partial pou emfanizei to avatar tou comment.user -->
        </div>
        <div class="w-100" style="overflow: hidden;">
          <div class="d-flex flex-row align-items-center"> <strong class="me-2"><%= link_to comment.user.username, user_profile_path(comment.user.username), target: '_top', class: 'username-color' %></strong> <span class="dot"> </span> <small class="ms-2 text-muted"> <%= time_ago_in_words(comment.created_at) %> ago </small> <span class="ms-2 text-muted"> #<%= comment.id %> </span>
            <div class="d-flex ms-auto d-none"
              data-controller='check-author'
              data-check-author-author-id-value='<%= comment.user.id %>' > <!-- elegxw opws kai sto post partial, an o current user einai o comment author gia na emfanisw ta edit kai delete buttons -->
              <%#= link_to "Edit", edit_post_comment_path(comment.post, comment), class: "me-2" %>
              <!-- sto route.rb kanw resources :comments, kai etsi exw to path gia edit kai delete comment xwris na xreiazetai to post_comment_path -->
              <%= link_to edit_comment_path(comment), class: "btn btn-sm shadow-none me-1" do %> <!-- edit, kanei replace to comment me thn edit form -->
                <i class="bi bi-pencil-fill"></i>
              <% end %>
              <%= button_to comment_path(comment), class: "btn btn-sm shadow-none", method: :delete, data: { confirm: "Are you sure?" } do %> <!-- destroy -->
                <i class="bi bi-trash-fill"></i>
              <% end %>
            </div>
          </div>
          <p class="text-justify ms-1 mb-0"><%= comment.body %></p>
          <!-- REPLY FORM -->
          <!-- xrhsimopoiw to collapse tou bootstrap gia na emfanizw kai na kryvw th reply form se ena comment -->
          <button class="btn reply-btn btn-sm bi bi-reply-fill shadow-none p-0" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample-<%= comment.id %>" aria-expanded="false" aria-controls="collapseExample"> 
            Reply
          </button>
          <div class="collapse" id="collapseExample-<%= comment.id %>">
            <div class="mt-2" id="new_com">
              <%= render partial: "comments/form", locals: { comment: Comment.new, post: comment.post, parent: comment } %> <!-- eimai mesa sto parent comment opou kanw render ti form, opote prepei na perasw san parent to comment sto opoio thelw na apanthsw. -->
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/comments/_comment_avatar.html.erb
<!-- partial pou emfanizei to avatar tou kathe xrhsth 
An pame to pontiki panw sto avatar emfanizetai ena popup me to avatar megalytero,
to username kai tin hmeromhnia eggrafhs tou user -->
<span class="hoverWrapper">
  <%= link_to user_profile_path(comment.user.username), target: "_top" do %>  <!-- avatar san link gia to profil tou user -->
    <% if comment.user.avatar.attached? %>
      <%= image_tag comment.user.avatar.variant(resize: "40x40!"), class: "rounded-circle"%>
    <% else %>
      <%= image_tag comment.user.gravatar_url, width: 40, class: "rounded-circle"%>
    <% end %>
  <% end %>
  
  <div class="card p-1" id="hoverContent">
    <div class="d-flex justify-content-center p-2">
      <% if comment.user.avatar.attached? %>
        <%= image_tag comment.user.avatar.variant(resize: "100x100!"), class: "rounded-circle"%>
      <% else %>
        <%= image_tag comment.user.gravatar_url, width: 100, class: "rounded-circle"%>
      <% end %>
    </div>
    <div class="card p-1 post-edit">
      <div class="border-bottom border-secondary text-center">
        <%= comment.user.username %>  
      </div>
      <span class="text-center">
        Joined: <%= comment.user.created_at.strftime("%B %Y") %>
      </span>
      <span class="text-center">
        <%= pluralize(comment.user.posts.count, "Post") %>
      </span>
    </div>
  </div>
</span>

app/views/comments/_comment_with_replies.html.erb
<%= turbo_stream_from comment, :comments %> <!-- stream pou akouei gia updates sto comment, alla me target ta chrildren comments tou -->

<div id="<%= dom_id(comment) %>_with_comments">
  <%= render comment %> <!-- kanw render to partial _comment.html.erb pou emfanizei to comment -->

  <!-- An to comment exei replies se auto, dhladh children comments, kanw render to collection comment.comments -->
  <!-- Etsi, gia kathe child, ksanakanw render to partial comment_with_replies, to opoio kanei render to idio to child comment, kai se periptwsh pou auto einai parent allwn comment, emfanizei kai auta k.o.k-->
  <div class="comment-border" id="<%= dom_id(comment) %>_comments"> <!-- dom_id gia to comment.rb-->
    <%= render partial: "comments/comment_with_replies", collection: comment.comments.includes(:user).order(id: :desc), as: :comment %>
  </div>
</div>

app/views/comments/_count.html.erb
<%= pluralize(count, "Comment") %>

app/views/comments/_form.html.erb
<!-- form gia to create kai to edit tou comment -->
<!-- otan kanw submit, i forma ginetai clear me ton stimulus controller reset_form -->
<%= form_with(model: [post, comment], remote: true, data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }) do |form| %>  <!-- remote true gia na kanw sumbit me enter -->
  <% if comment.errors.any? %>  <!-- sto edit, emfanizw ta error messages ean kati paei strava. sto create, deixnw error flash message mesw tou comments controller -->
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <!--  pernaw to parent_id, ean yparxei-->
  
  <% if !parent.nil? %>
    <div class="field">
      <%= form.hidden_field :parent_id, value: "#{parent.id}" %>
    </div>
  <% end %>
  

  <div class="d-flex align-items-center">
    <%= form.text_field :body, placeholder: "Leave a reply", autocomplete: 'off', class: "form-control" %>
    <%= form.submit  class: "btn btn-sm comment-new-btn shadow-none ms-1" %>
  </div>
  <!-- mono sto edit, to emfanizw gia na mporw na kanw replace to frame ean thelw na akyrwsw to edit -->
  <%#= link_to "Cancel Edit", comment, class: "btn btn-sm btn-link bi bi-x shadow-none" if form.object.persisted? %>
<% end %>

app/views/comments/_next_comment_page.html.erb
<!-- idia logikh me to pagination gia ta posts -->
<% if @more_pages %>
  <%= turbo_frame_tag(
        "comments-page-#{@next_cursor}",
        #autoscroll: true,
        loading: :lazy,
        src: post_path(cursor: @next_cursor), # xrhsimopoiw to post_path afou eimai sto show tou posts controller
        target: "_top"
      ) do %>
    <div class="d-flex justify-content-center mt-2">
      <div class="spinner-border text-secondary" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
    </div>
  <% end %>
<% else %>
  <p class=" mt-2 text-center fw-bold fst-italic">You've reached the end of comments.</p>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<!-- to kanw mesw tou broadcast se olous tous users sto comment.rb -->
<%#= turbo_stream.remove(@comment) %>

<!-- emfanizw to flash message ston current user pou diagrafei to comment -->
<%= render_flash_messages %>

app/views/comments/edit.html.erb
<!-- turbo frame me to idio id gia na kanw replace to frame tou comment -->
<%= turbo_frame_tag @comment do %>
  <div class="comment-edit card p-1 mt-2">
    <div class="d-flex justify-content-between">
      <h4 class="header m-2">Editing Comment <span class="text-muted">#<%= @comment.id %></span></h4>
      <%= link_to @comment, class: "btn shadow-none" do %>
        <i class="bi bi-x-circle fs-4"></i>
      <% end %>
    </div>
    <%= render "form", comment: @comment, post: @comment.post, parent: @comment.parent %> <!-- pernaw ta locals sto form giati xrhsimopoiw to edit _comment_path kai oxi edit_post_comment_path-->
  </div>
<% end %>

app/views/comments/scrollable_comment_list.html.erb
<!-- idia logikh me to pagination gia ta posts -->
<%= turbo_frame_tag "comments-page-#{@cursor}" do %>
  <%= render partial: "comments/comment_with_replies", collection: @comments, as: :comment %>
  <%= render partial: "comments/next_comment_page" %>
<% end %>

app/views/comments/show.html.erb
<%= turbo_frame_tag @comment do %>
  <%= render @comment %>
<% end %>

app/views/comments/update.turbo_stream.erb
<!-- kanw replace to comment ston user pou to kanei update -->
<!-- den xreiazetai aparaithta, afou kanw broadcast update sto comment.rb-->
<%= turbo_stream.replace @comment %>
<!-- render to flash message ston user-->
<%= render_flash_messages %>