config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  get 'users/profile'
  get 'users/show'
  devise_for :users
  
  resources :posts do
    resources :comments
    resource :likes, only: :show
  end

  resources :comments

  resources :rooms do
    resources :messages, shallow: :true
    collection do
      post :search
    end
  end

  resources :embeds, only: [:create], constraints: { id: /[^\/]+/ } do
    collection do
      get :patterns
    end
  end
  
  resources :mentions, only: [:index]
  
  get ':username', to: 'users#profile', as: 'user_profile'  #user_path(user.username) gia na parw to profile enos user
  get 'user/:id', to: 'users#show', as: 'user'  # private chat room
  root 'posts#index'
end

app/views/shared/_flash.html.erb
<!-- flash message  -->
<!-- to kanw render se olo to application -->

<!-- Kathe message einai connected ston stimulus controller removals, o opoios
 afairei to flash message apo to DOM, otan to animation teleiwsei -->
<% flash.each do |flash_type, message| %>
  <% if flash_type == "alert" %>
    <div 
      class="flash__message alert alert-danger" 
      role="alert"
      data-controller="removals"
      data-action="animationend->removals#remove"
    >
      <%= message %>
    </div>
  <% elsif flash_type == "notice" %>
    <div 
      class="flash__message alert alert-success" 
      role="alert"
      data-controller="removals"
      data-action="animationend->removals#remove"
    >
      <%= message %>
    </div>
  <% else %>
    <div
      class="flash__message"
      data-controller="removals"
      data-action="animationend->removals#remove"
    >
      <%= message %>
    </div>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<!-- BOOTSTRAP NAVBAR OPTIONS -->
<nav class="navbar navbar-expand-sm navbar-dark bg-dark sticky-top p-0">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">Fanapp</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="nav navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= root_path %>">Fanwall</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= rooms_path %>">Chat</a>
        </li>
      </ul>
      <span class="navbar-text ms-auto"><%= Time.zone.now %></span> <!-- metafora apo to application.html.erb sto navbar -->
      <ul class="nav navbar-nav ms-auto">
        <li class="nav-item dropdown">
          <% if current_user %>
    		    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    		      <% if current_user.admin? %>
                <h4 class="badge rounded-pill bg-success me-1 m-0">ADMIN</h4>
              <% end %>
              <% if current_user.avatar.attached? %>
        			  <%= image_tag current_user.avatar.variant(resize: "40x40!"), class: "rounded-circle" %>
        		  <% else %>
        			  <%= image_tag current_user.gravatar_url, height: 40, width: 40, class: "rounded-circle"%>
        		  <% end %>
              <span class="username-color"><%= current_user.username %></span>
    		    </a>
            <div class="dropdown-menu dropdown-menu-end dropdown-bg" aria-labelledby="navbarDropdown">
              <a class="dropdown-item bi bi-person-circle" href="<%= user_profile_path(current_user.username) %>"> <span class="ms-2">My Profile</span></a>
              <a class="dropdown-item bi bi-person-lines-fill" href="<%= edit_user_registration_path %>"> <span class="ms-2">Edit Account</span></a>
              <div class="dropdown-divider"></div>
              <%= button_to destroy_user_session_path, method: :delete, class: 'dropdown-item', "data-turbo": false do %>
                <i class="bi bi-box-arrow-left"></i> <span class="ms-2">Logout</span>
              <% end %>
            </div>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>