config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  get 'users/profile'
  get 'users/show'
  devise_for :users
  
  resources :posts do
    resources :comments
    resource :likes, only: :show
  end

  resources :comments

  resources :rooms do
    resources :messages, shallow: :true
    collection do
      post :search
    end
  end

  resources :embeds, only: [:create], constraints: { id: /[^\/]+/ } do
    collection do
      get :patterns
    end
  end
  
  resources :mentions, only: [:index]
  
  get ':username', to: 'users#profile', as: 'user_profile'  #user_path(user.username) gia na parw to profile enos user
  get 'user/:id', to: 'users#show', as: 'user'  # private chat room
  root 'posts#index'
end

app/models/post.rb
class Post < ApplicationRecord
  include ActionView::RecordIdentifier # gia na xrhsimopoiw to dom_id se ena model
  include ApplicationHelper

  belongs_to :user # kathe post anhkei se ena user
  has_many :comments, dependent: :destroy # ena post exei polla comments, otan diagrafw to post diagrafontai kai auta
  has_many :likes, dependent: :destroy # ena post exei polla likes, otan diagrafw to post diagrafontai kai auta

  #rich text field
  has_rich_text :body
  validates :body, presence: true #den prepei na einai keno
 
  # SEARCH SCOPES

  # search_text scopepou kanei join sto ActionText::RichText model, kanontas ena ILIKE keyword query
  # To ILIKE den ypologizei gia HTML characters, px an psaksw gia mia ekfrash kai mia apo tis lekseis ths sto body tou post einai mesa se <strong>leksh</strong> 
  # den tha kanei match me to content
  # Gia to logo auto, prosthetw ena plain_text_body column sto action_text_rich_texts table, wste ta ActionText::RichText models na grafoun kai na kanoun search se auto.
  # orizw ena callback before_save, opou se kathe create h update tou Post kalw tin to_plain_text, pou afairei kathe HTML syntax kai afhnei mono to text content tou body sto plain_text_body.
  # Gia na mhn einai periorismeno mono sto Post model, kai na exw th dunatothta gia full text search se ola ta models me rich_rext_content kanw to ekshs:
  # config/initializers/action_text_rich_text.rb
  scope :search_text, ->(query) { joins(:rich_text_body).merge(ActionText::RichText.with_body_containing(query)) }
  # search_username scope, psaxnw stous users gia matching username me to query gia na epistrepsw ola ta posts tou user pou psaxnw
  # "#{username}" prepei na grapsw akrivws to username
  # px. an psaksw "mi" den tha vrei ton xrhsth "mixalhs"
  # "%#{username}%" kanei match usernames pou periexoun ti frash h to xarakthra pou psaxnw. 
  # px. an psaksw "mi" kai yparxoun xrhstew "mixalhs" kai "mixalhs125" tha kanei match kai ta dyo
  # Xrhsimopoiw ILIKE pou einai case-insensitive, px. "MixALhs" tha vrei to username "mixalhs"
  scope :search_username, ->(username) { joins(:user).where('users.username ILIKE ?', "#{username}") }


  #Broadcast

  # gia to broadcast xreiazomai sto index view:
  # ena turbo_stream_from :posts
  # ena default target <div id="posts">
  # ena default partial 'posts/_post'
  # etsi mporw na kanw broadcast kathe create update kai destroy record

  # add on top of DOM ID
  # target: HTML element with an ID DOM ID, <div id="posts">
  # to HTML tou created post ginetai broadcasted se olous tous xrhstes pou einai subscrribed to stream :posts
  # kai prostithetai panw (prepend) apo ti lista me ola ta posts.
  after_create_commit do 
    broadcast_prepend_to :posts, target: "posts", partial: "posts/post_to_broadcast", locals: {  post: self } 
    update_post_counter
  end
  
  # Gia na kanw broadcast to updated post se olous tous users pou einai subscribed sto stream.
  # O logos pou den to kanw einai giati den exw vrei tropo na elegxw an o kathe user exei kanei hdh like sto post,
  # logw tou oti den mporw na xrhsimopoihsw to current_user tou devise me to broadcast.
  # etsi to partial post_to_broadcast to xrhsimopoiw mono se kathe create opou kanenas user den exei kanei akomh like sto post.
  # opote to icon gia to like tha einai to default gia ena neo post (like_icon)

  # Stin update tou post controller, kanw replace to post mono gia ton user pou to kanei edit se real time, 
  # mesw tou turbo_stream.replace @post, kai etsi pairnw to swsto like icon tou current_user

  after_update_commit do 
    broadcast_update_to :posts, partial: "posts/post_to_broadcast", locals: { post: self }
  end

  # destroy to post 
  after_destroy_commit do 
    broadcast_remove_to :posts, target: self # afairei to post apo ti lista me ta post gia olous tous xrhstes
    update_post_counter
  end 

  #ypologizw ta like tou post analoga me to choice tou kathe like
  def like_count
    likes.sum(:choice)
  end

  private 

  #update ton post_counter se olous tous xrhstes, otan dhmiourgeitai h diagrafetai post.
  #exw ena id='post_counter' sto index view pou ginetai update meta apo kathe create kai destroy
  def update_post_counter
    broadcast_update_to :posts, target: "post_counter", partial: 'posts/count', locals: { count: Post.count }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ActionView::RecordIdentifier
  before_action :set_post, only: %i[ edit update destroy ]
  #before_action :is_author?, only: [:edit, :update, :destroy]
  POSTS_PER_PAGE = 5
  COMMENTS_PER_POST_PAGE = 5
  # GET /posts
  # Sto index pou emfanizw ola ta posts, thelw na kanw kai to search
  # Ean o user kanei search sta dyo search forms, yparxoyn 3 periptwseis
  # Gia kathe mia apo autes, allazw to @posts pou xrhsimopoiw gia na kanw render ta posts
  def index
    # PERIPTWSH 1 - An exei ginei submit mono to search gia query
    if params[:query].present? && !params[:username].present?
      @cursor = params[:cursor]
      @posts = Post
                    .search_text(params[:query])  # thelw mono ta posts pou periexoun ta params[:query]
                    .where(@cursor ? ["posts.id < ?", @cursor] : nil)
                    .order(id: :desc).take(POSTS_PER_PAGE)
      @next_cursor = @posts.last&.id
      @more_pages = @next_cursor.present? && @posts.count == POSTS_PER_PAGE

      render "scrollable_list" if params[:cursor]
    # PERIPTWSH 2 - An exei ginei submit mono to search gia username
    elsif  params[:username].present? && !params[:query].present?
      @cursor = params[:cursor]
      @posts =  Post
                    .search_username(params[:username]) # thelw mono ta posts pou periexoun ta params[:username]
                    .where(@cursor ? ["posts.id < ?", @cursor] : nil)
                    .order(id: :desc).take(POSTS_PER_PAGE)
      @next_cursor = @posts.last&.id
      @more_pages = @next_cursor.present? && @posts.count == POSTS_PER_PAGE

      render "scrollable_list" if params[:cursor]
    # PERIPTWSH 3 - An exei ginei submit kai to search gia query kai gia username
    elsif  params[:query].present? && params[:username].present?
      @cursor = params[:cursor]
      @posts =  Post
                    .search_username(params[:username]).search_text(params[:query]) # thelw ta posts pou periexoun ta params[:username] kai params[:query]
                    .where(@cursor ? ["posts.id < ?", @cursor] : nil)
                    .order(id: :desc).take(POSTS_PER_PAGE)
      @next_cursor = @posts.last&.id
      @more_pages = @next_cursor.present? && @posts.count == POSTS_PER_PAGE

      render "scrollable_list" if params[:cursor]
    # NO SEARCH - ean den exei ginei search (default) kanw render ola ta posts se descending order
    else 
      # CURSOR-BASED PAGINATION
      # se oles tis periptwseis den thelw na emfanizontai ola ta post se mia selida alla thelw mono POSTS_PER_PAGE ana selida
      # kathe unique key pou mporw na kanw order by mporei na xrhsimopoiithei ws cursor, opote tha xrhsimopoiwsw to id twn posts san cursor
      # kathe epomeno post tha exei id < apo to cursor, etsi akoma kai an diagrafei to post tou cursor, to epomeno post tha ginei returned swsta

      # Thelw na petyxw kati san infinite scrolling, opou h epomenh selida twn posts emfanizetai katw apo to teleutaio kathe fora pou ftanw sto telos tis selidas
      # Epeidh tin idia stigmh thelw na kanw create kai delete posts se real time, auto shmainei pws otan afairw ena post allazei kai i lista twn posts se kathe selida
      # kai ean xrhsimopoiousa ena gem (px pagy) pou xrhsimopoiei offset pagination, den tha epistrefontan ta swsta posts tis epomenhs selidas
      # px. an exw [A, B, C, D, E, F] posts kai kathe selida exei 3 h prwth tha exei ta [A, B, C] 
      # ean afairesw to B tha exoun meinei [A, C] stin prwth selida kai synolika sto database [A, C, D, E, F]
      # Parolo pou sto 1o page exw mono 2 results anti gia 3, to 2o page tha xrhsimopoihsei tin updated database.
      # Etsi otan kanw request to 2o page, tha nomizei oti to D einai meros tou 1ou page, kai tha prosthesei ta epomena 3 posts (se auth thn periptwsh ta 2 pou menoun) : [A, C, E, F]
      # To post D leipei.
      # Me to cursor based pagination, anti na zhthsw ta posts tou next page, zhtaw to epomeno post meta to C, ara tha parw to swsto set twn post: [A, C, D, E, F]
      @cursor = params[:cursor]
      @posts = Post
                    .where(@cursor ? ["id < ?", @cursor] : nil) # to epomeno post na exei mikrotero id apo to id tou cursor
                    .order(id: :desc)                           # ola ta posts kata fthinousa seira
                    .take(POSTS_PER_PAGE)                       # kathe fora thelw na ginontai return POSTS_PER_PAGE (px. 5) posts
      
      @next_cursor = @posts.last&.id  # thetw next_cursor to teletaio post tis listas
      @more_pages = @next_cursor.present? && @posts.count == POSTS_PER_PAGE
      render "scrollable_list" if params[:cursor] # kanw render to template scrollable_list mesw tou unique id tou turbo_frame tou next_page partial
                                                  # se auto kanw render ta posts me id < cursor kai sth synexeia ksanakanw render to next_page partial
    end
    #mporw na dhmiourghsw neo post apo to index
    @post = Post.new
  end

  # GET /posts/1
  def show
    @post = Post.find_by(id: params[:id])
    
    #an enas user thelei na dei ena post poy exei diagrafei, ton kanw redirect sto index
    #px an vlepei to post kai ekeinh th stigmh o owner to diagrapsei, an kanei refresh, tha metavei sto index
    if @post.nil?
      #@pagy, @posts = pagy(Post.order(created_at: :desc), items: 5)
      #flash.now[:alert] = "Post was not found"
      #render "index"
      redirect_to posts_path, alert: "Post was not found"
    else
      #GEARED PAGINATION 
      #@comments = set_page_and_extract_portion_from @post.comments.where(parent_id: nil).includes(:user, :post, comments: :user).order(id: :desc), per_page: [5]
      
      #CURSOR-BASED PAGINATION COMMENTS
      #idios tropos me ta post me ta antistoixa views
      @cursor = params[:cursor]
      @comments = @post.comments
                                .where(parent_id: nil)  #kanw pagination mono sta top comments pou den exoun parent (Dhladh auta pou einai apanthsh se post kai oxi kapoio allo comment)
                                .where(@cursor ? ["id < ?", @cursor] : nil)
                                .includes(:user, :post, comments: :user) # improve performance, includes :user, kanw fetch olous tous users pou sysxetizontai me ta comments
                                .order(id: :desc).take(COMMENTS_PER_POST_PAGE)
      @next_cursor = @comments.last&.id
      @more_pages = @next_cursor.present? && @comments.count == COMMENTS_PER_POST_PAGE
      render "comments/scrollable_comment_list" if params[:cursor] 
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        #create.turbo_stream.erb
        #update the page mono gia ton current_user pou kanei to action
        #katharizei ti forma kai deixnei to flash message mono ston current user
        format.turbo_stream { flash.now[:notice] = "Post #{@post.id} was successfully created." }
        format.html { redirect_to posts_path, notice: "Post #{@post.id} was successfully created." }
      else
        flash.now[:alert] = "Something went wrong"

        format.turbo_stream do
          render turbo_stream: [
            #kalw apo ton application_helper gia na kanw render to flash message
            helpers.render_flash_messages 
          ]
        end
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  def update

    if current_user != @post.user
      respond_to do |format|
        format.turbo_stream { flash.now[:alert] = "You don't have the rights to edit this post." }
        format.html { redirect_to @post, alert: "You don't have the rights to edit this post." }
      end
    else
      respond_to do |format|
        if @post.update(post_params)
          #update.turbo_stream.erb
          #deixnei to flash message mono ston current user
          format.turbo_stream { flash.now[:notice] = "Post #{@post.id} was successfully updated." }
          format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /posts/1
  def destroy
    #to xrhsimopoiousa otan edeixna ta buttons [edit, delete] se olous tous users kai oxi mono ston owner

    if current_user != @post.user
      respond_to do |format|
        flash.now[:alert] = "You don't have the rights to delete this post."
        format.turbo_stream do 
          render turbo_stream: [
            helpers.render_flash_messages
          ]
        end
        format.html { redirect_to @post, alert: "You don't have the rights to delete this post." }
      end
    else
      @post.destroy
      
      respond_to do |format|
        #destroy.turbo_frame.erb
        #deixnei to flash message mono ston current user
        format.turbo_stream { flash.now[:notice] = "Post #{@post.id} was successfully destroyed." }
        format.html { redirect_to posts_path, notice: "Post was successfully destroyed." }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      # Avoid N+1 queries
      # Preload both body and attachments.
      @post = Post.with_rich_text_body_and_embeds.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      #gia na dexetai rich_text prepei na kanw permit to attribute body
      params.require(:post).permit(:body)
    end

    #an o user den einai o owner tou post den mporei na to kanei edit kai delete
    def is_author?
      redirect_to @post, alert: "You don't have the rights to edit or delete this post." unless @post.user == current_user
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_count.html.erb
Total posts: <%= count %>

app/views/posts/_likes_link.html.erb
<div data-controller='check-current-user' class='d-none'>
  <!-- like -->
  <!-- pernaw to post, to choice pou edw kanw mono upvotes, kai format turbo_stream -->
  <%= link_to post_likes_path(post, choice: :upvote, format: :turbo_stream), class: "btn shadow-none like-btn" do %>
    <span id='<%= dom_id(post)%>_upvote_label'>  <!-- target pou kanw broadcast mono ston current user to swsto icon meta apo kathe tou like h undo like -->
      <!-- ApplicationHelper -->
      <%= like_label(post, static) %> <!-- emfanizw to katallhlo like icon -->
    </span>
    <span id='<%= dom_id(post)%>_count' class="like-count">  <!-- kanw broadcast to updated like_count gia kathe like h undo like-->
      <%= post.like_count %>  <!-- emfanizw ton arithmo twn likes mesw ths like_count tou post.rb -->
    </span>
  <% end %>
  <!-- dislike -->
  <%#= link_to post_likes_path(post, choice: :downvote, format: :turbo_stream), class: "btn shadow-none" do %>
    <!--span id='<%= dom_id(post) %>_downvote_label' class='text-danger'-->
      <!-- ApplicationHelper -->
      <%#= dislike_label(post, static) %>
    <!--/span-->
  <%# end %>
</div>

app/views/posts/_post.html.erb
<!-- kathe post einai mesa se ena turbo frame me ena unique id: "post#{post_id}" 
  mporw na xrhsimopoihsw to helper dom id gia na exw ena tetoio unique id gia kathe turbo_frame_tag
  xreiazomai ena turbo frame me to idio id kai gyrw apo ti forma tou posts#edit page 
  etsi otan pataw na kanw edit ena post, h forma kanei replace to post on the spot
  otan pathsw na kanw update to post, to frame pou perieixe th forma, ginetai replaced apo to frame me to updated post -->

<%= turbo_frame_tag dom_id(post) do %>
  <div class="card border p-1 mt-2">
    <div class="d-flex flex-row justify-content-between align-items-center p-2">
      <div class="d-flex flex-row align-items-center feed-text">
        <%= render partial: 'posts/post_avatar', locals: { post: post } %>
        <div class="d-flex flex-column flex-wrap ms-2">
          <div class="d-flex align-items-center">
            <span class="fw-bold"><%= link_to post.user.username, user_profile_path(post.user.username), target: "_top", class: 'username-color' %></span> <!-- emfanizw to username san link gia to profil tou user -->
            <span class="ms-2 dot"> </span>
            <span class="ms-2 text-muted">#<%= post.id %></span>
          </div>
          <span class="text-black-50 time">
            <%= post.updated_at.strftime("%H:%M %A, %B %e, %Y") %>
          </span>
        </div>
      </div>

      <!-- DROPDOWN TO EDIT AND DELETE-->
      <!-- elegxw an o current user einai kai author tou post wste na tou emfanizw ta buttons gia edit kai delete
      Epeidh to current_user einai global helper tou gem devise, den mporei na xrhsimopoihthei se ena partial pou ginetai broadcast me turbo stream
      Partials used for turbo streaming have to be free of global references, as they’re rendered by the ApplicationRenderer, not within the context of a specific request. 
      Pairnw to current-user-id apo ena meta(tag) sto head tou application.html wste na to xrhsimopoihsw mesa ston controller -->
      <!-- sto _post partial mporousa na kanw kanonika ton elegxo me to current_user [if current_user == post.user] kathws den to kanw broadcast -->
      <!-- sto _post_to_broadcast einai aparaithto wste otan kanw create h update ena post na mhn yparxoun oi epiloges gia edit h delete stous mh authors -->
      <div class="d-flex d-none"
        data-controller='check-author'
        data-check-author-author-id-value='<%= post.user.id %>' >
        <div class="dropdown">
          <button type="button" class="btn shadow-none dropdown" data-bs-toggle="dropdown">
            <i class="bi bi-three-dots-vertical"></i>
          </button>
          <div class="dropdown-menu dropdown-menu-end dropdown-bg"> <!-- dropdown me tis epiloges edit kai delete post -->
            <!-- EDIT BUTTON -->
            <%= link_to edit_post_path(post), class: 'dropdown-item btn shadow-none bi bi-pencil-fill', data: { turbo_frame: dom_id(post) } do %>
              <span class="ms-2">Edit Post</span>
            <% end %>
            <!-- DELETE BUTTON-->
            <% if action_name == 'show' && controller_name == 'posts' %> <!-- otan eimai sto show tou post, thelw otan diagrafetai to post na kanw redirect sto index me ola ta post, gi auto den thelw na kanw destroy as turbo_stream alla as HTML -->
              <%= link_to polymorphic_path(post, format: :html), method: :delete, data: { confirm: 'Are you sure?' }, class: 'dropdown-item btn btn-danger bi bi-trash3-fill' do %>
                <span class="ms-2">Delete Post</span>
              <% end %>
            <% else %> <!-- se kathe allh periptwsh den thelw na kanw redirect ton user poy kanei delete  opote kanw destroy as turbo_stream -->
              <%= button_to  post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'dropdown-item btn btn-danger' do %>  
                <i class="bi bi-trash3-fill"></i> <span class="ms-2">Delete Post</span>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <!-- TRUNCATE POST BODY -->
    <!-- stimulus controller poy emfanizei ena button Show more otan to post body pianei perissotero apo x grammes
    wste an to post pianei polles grammes na mhn emfanizetai oloklhro. 
    Kanontas click, emfanizetai oloklhro to post me thn epilogh Show less pou to epanaferei -->
    <div class="p-1 border-bottom" data-controller="link-new-tab">  <!-- o link_new_tab_controller, anoigei kathe link tou post.body se neo tab otan kanw click sto link -->
      <div data-controller="read-more" data-read-more-lines-value="3"
          data-read-more-hide-class="hide"
          data-read-more-truncate-class="line-clamp"
          data-action="resize@window->read-more#render">
        <div data-read-more-target="content">
          <%= post.body %>
        </div>
        <button class="btn btn-link shadow-none hide p-0 more-btn" role="button" tabindex=0 data-read-more-target="moreButton" data-action="read-more#showMore">
          Show more
        </button>
        <button class="btn btn-link shadow-none hide p-0 more-btn" role="button" tabindex=0 data-read-more-target="lessButton" data-action="read-more#showLess">
          Show less
        </button>
      </div>
    </div>
    <div class="d-flex mt-1 ms-auto">
      <!-- LIKES -->
      <!-- edw kanw render to partial pou xeirizetai to button gia ta likes -->
      <%= render 'posts/likes_link', post: post, static: nil %>

      <!-- to link gia na dw ena post einai mesa se turbo frame,
      sto posts#show den yparxei turbo frame me to idio id
      vazw link na kanei target to "_top" frame wste na kanei replace olh th selida -->
      <%= link_to post, target: "_top", class: "btn shadow-none comments-btn" do %>
        <i class="bi bi-chat"></i>
        <!-- live update tou comment count -->
        <span id='<%= dom_id(post)%>_comments_counter' class="comment-count"> <!-- target pou kanw broadcast to comments_count gia kathe neo h deleted comment -->
          <%= post.comments_count %>
        </span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/posts/_post_to_broadcast.html.erb
<!-- to post partial pou ginetai broadcast otan se kathe create h update enos post-->
<%= turbo_frame_tag dom_id(post) do %>
  <div class="card border p-1 mt-2">
    <div class="d-flex flex-row justify-content-between align-items-center p-2">
      <div class="d-flex flex-row align-items-center feed-text">
        <%= render partial: 'posts/post_avatar', locals: { post: post } %>
        <div class="d-flex flex-column flex-wrap ms-2">
          <div class="d-flex align-items-center">
            <span class="fw-bold"><%= link_to post.user.username, user_profile_path(post.user.username), target: "_top", class: 'username-color' %></span>
            <span class="ms-2 dot"> </span>
            <span class="ms-2 text-muted">#<%= post.id %></span>
          </div>
          <span class="text-black-50 time">
            <%= post.updated_at.strftime("%H:%M %A, %B %e, %Y") %>
          </span>
        </div>
      </div>
      <div class="d-flex ms-auto">  <!-- otan kanw broadcast create h update ena post pou periexei embed tweet, gia kapoio logo den metatrepetai to blockquote se iframe kai to tweet den emfanizetai swsta ektos an kanw full page refresh -->
        <%= link_to post, class: 'btn shadow-none' do %> <!-- epeidh thelw ta post an emfanizontai se real time, gia na mhn anagkazw ton xrhsth na kanei full page refresh gia na dei to tweet -->
          <i class="fa-solid fa-arrow-rotate-right reload-frame"></i> <!-- emfanizw ena reload icon wste enas user na mporei na kanei reload to frame pou periexei ena post -->
        <% end %> <!-- otan o user kanei reload to frame, to tweet emfanizetai swsta -->
      </div>
      <div class="d-flex d-none"
        data-controller='check-author'
        data-check-author-author-id-value='<%= post.user.id %>' >
        <div class="dropdown">
          <button type="button" class="btn shadow-none dropdown" data-bs-toggle="dropdown">
            <i class="bi bi-three-dots-vertical"></i>
          </button>
          <div class="dropdown-menu dropdown-menu-end">
            <!-- EDIT BUTTON -->
            <%= link_to edit_post_path(post), class: 'dropdown-item btn shadow-none bi bi-pencil-fill', data: { turbo_frame: dom_id(post) } do %>
              <span class="ms-2">Edit Post</span>
            <% end %>
            <!-- DELETE BUTTON-->
            <% if action_name == 'show' && controller_name == 'posts' %> <!-- otan eimai sto show tou post, thelw otan diagrafetai to post na kanw redirect sto index me ola ta post, gi auto den thelw na kanw destroy as turbo_stream alla as HTML -->
              <%= link_to polymorphic_path(post, format: :html), method: :delete, data: { confirm: 'Are you sure?' }, class: 'dropdown-item btn btn-danger bi bi-trash3-fill' do %>
                <span class="ms-2">Delete Post</span>
              <% end %>
            <% else %> <!-- se kathe allh periptwsh den thelw na kanw redirect ton user poy kanei delete  opote kanw destroy as turbo_stream -->
              <%= button_to  post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'dropdown-item btn btn-danger' do %>  
                <i class="bi bi-trash3-fill"></i> <span class="ms-2">Delete Post</span>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <!-- TRUNCATE POST BODY -->
    <div class="p-1 border-bottom" data-controller="link-new-tab">
      <div data-controller="read-more" data-read-more-lines-value="3"
          data-read-more-hide-class="hide"
          data-read-more-truncate-class="line-clamp"
          data-action="resize@window->read-more#render">
        <div data-read-more-target="content">
          <%= post.body %>
        </div>
        <button class="btn btn-link shadow-none hide p-0 more-btn" role="button" tabindex=0 data-read-more-target="moreButton" data-action="read-more#showMore">
          Show more
        </button>
        <button class="btn btn-link shadow-none hide p-0 more-btn" role="button" tabindex=0 data-read-more-target="lessButton" data-action="read-more#showLess">
          Show less
        </button>
      </div>
    </div>
    <div class="d-flex mt-1 ms-auto">
      <!-- pernaw to static true wste h like_label na kanei broadcast to icon pou deixnei oti o user den exei kanei like sto post , otan kanw broadcast create ena neo post -->
      <!-- gia to broadcast update otan ginetai edit ena post, epeidh den mporw na xrhsimopoihsw to current_user se partial,
          tha emfanizei panta to like_icon( pou deixnei oti o user den exei kanei like), akoma kai stous users pou exoun kanei hdh like -->
      <!-- den exw vrei akomh kapoio tropo poy na mporw na elegxw an oi users stous opoious ginetai broadcast to udpate exoun kanei like sto post 
          opote pros stigmhs mporw na mhn kanw katholou broadcast update stous upoloipous users, kai na kanw live update mono ston current user pou kanei to edit, me turbo_stream.update ston controller. -->
      <%= render 'posts/likes_link', post: post, static: true %>
      
      <%= link_to post, target: "_top", class: "btn shadow-none comments-btn" do %>
        <i class="bi bi-chat"></i>
        <!-- live-update tou comment count -->
        <span id='<%= dom_id(post)%>_comments_counter' class="comment-count">
          <%= post.comments_count %>
        </span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/posts/create.turbo_stream.erb
<%#= turbo_stream.prepend "posts", @post %>

<!-- Turbo updates to turbo frame id "new_post" kai to kanei adeio -->
<%= turbo_stream.update Post.new, "" %> 
<!-- kanw render stin othoni to analogo flash apo ton controller -->
<%= render_flash_messages %>